package localization

var en = Translation{
	Layout: LayoutLabels{
		NavHome:           "Home",
		NavGenerations:    "Generations",
		NavGen1:           "1st Generation",
		NavGen2:           "2nd Generation",
		NavGen3:           "3rd Generation",
		NavGen4:           "4th Generation",
		NavGen5:           "5th Generation",
		NavGen6:           "6th Generation",
		NavGen7:           "7th Generation",
		NavComingSoon:     "Coming soon:",
		SearchPlaceholder: "Search...",
		CurrentLang:       "English",
		LangEnLabel:       "English",
		LangFrLabel:       "Français",
		FooterCopyright:   "© 2026 PokéGrep. All rights reserved.",
		FooterPoweredBy:   "Powered by",
		FooterPokeApiUrl:  "https://pokeapi.co",
		FooterPokeApiText: "PokéAPI",
		FooterGithubUrl:   "https://github.com/PokeGrep/PokeGrep.github.io",
		FooterGithubText:  "GitHub",
	},
	Generation: GenerationLabels{
		SearchPlaceholder:   "Search by name or number...",
		FilterAll:           "All",
		ActiveFilters:       "Active filters:",
		NoResultsTitle:      "No Pokémon matches your criteria",
		NoResultsSubtitle:   "Try adjusting the search query or filters.",
		ResetFilters:        "Reset Filters",
		NoActiveFiltersText: "No active filters (All Pokémon)",
	},
	Pokemon: PokemonTemplateLabels{
		Characteristics: CharacteristicsBlock{
			Title:                 "Characteristics",
			Size:                  "Size",
			Weight:                "Weight",
			EggGroups:             "Egg Groups",
			WeaknessesResistances: "Resistances and Weaknesses",
			Stats:                 "Statistics",
		},
		EvolutionChain: EvolutionChainBlock{
			Title: "Evolution Chain",
		},
		Moveset: MovesetBlock{
			Title:       "Capacity list",
			Capacity:    "Capacity",
			Type:        "Type",
			Category:    "Category",
			Power:       "Power",
			Accuracy:    "Accuracy",
			Method:      "Method",
			GameDetails: "Details (Game)",
		},
		Localizations: LocalizationsBlock{
			Title:       "Localizations",
			Method:      "Method",
			Area:        "Area",
			GameVersion: "Versions",
			Levels:      "Levels",
		},
	},
}
