package localization

var fr = Translation{
	Layout: LayoutLabels{
		NavHome:           "Accueil",
		NavGenerations:    "Générations",
		NavGen1:           "1re Génération",
		NavGen2:           "2ème Génération",
		NavGen3:           "3ème Génération",
		NavGen4:           "4ème Génération",
		NavGen5:           "5ème Génération",
		NavGen6:           "6ème Génération",
		NavGen7:           "7ème Génération",
		NavComingSoon:     "Prochainement :",
		SearchPlaceholder: "Rechercher...",
		CurrentLang:       "Français",
		LangEnLabel:       "English",
		LangFrLabel:       "Français",
		FooterCopyright:   "© 2026 PokéGrep. Tous droits réservés.",
		FooterPoweredBy:   "Propulsé par",
		FooterPokeApiUrl:  "https://pokeapi.co",
		FooterPokeApiText: "PokéAPI",
		FooterGithubUrl:   "https://github.com/PokeGrep/PokeGrep.github.io",
		FooterGithubText:  "GitHub",
	},
	Generation: GenerationLabels{
		SearchPlaceholder:   "Rechercher par nom ou n°...",
		FilterAll:           "Tous",
		ActiveFilters:       "Filtres actifs :",
		NoResultsTitle:      "Aucun Pokémon ne correspond à votre recherche",
		NoResultsSubtitle:   "Essayez d'ajuster les filtres ou la recherche par nom.",
		ResetFilters:        "Réinitialiser",
		NoActiveFiltersText: "Aucun filtre actif (Tous les Pokémon)",
	},
	Pokemon: PokemonTemplateLabels{
		Characteristics: CharacteristicsBlock{
			Title:                 "Caractéristiques",
			Size:                  "Taille",
			Weight:                "Poids",
			EggGroups:             "Groupe d'œufs",
			WeaknessesResistances: "Résistances et Faiblesses",
			Stats:                 "Statistiques",
		},
		EvolutionChain: EvolutionChainBlock{
			Title: "Chaîne d'Évolution",
		},
		Moveset: MovesetBlock{
			Title:       "Liste des capacités",
			Capacity:    "Capacité",
			Type:        "Type",
			Category:    "Catégorie",
			Power:       "Puissance",
			Accuracy:    "Précision",
			Method:      "Méthode",
			GameDetails: "Détails (Jeu)",
		},
		Localizations: LocalizationsBlock{
			Title:       "Localisations",
			Method:      "Méthode",
			Area:        "Zone",
			GameVersion: "Versions",
			Levels:      "Niveaux",
		},
	},
}
